flush ruleset

table inet filter {
  set management {
    type ipv4_addr
    flags interval
    elements = { 172.17.1.0/24, 172.17.2.0/24 }
  }

  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept
    ct state invalid drop
    ct state { established, related } accept
    ip protocol icmp accept

    meta l4proto tcp jump input_tcp
    meta l4proto udp jump input_udp
  }

  chain input_tcp {
  }

  chain input_udp {
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
