name: kea
services:
  database:
    image: database
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: database
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./database/nftables.conf:/etc/nftables.conf:ro
      - database:/var/lib/postgresql
    networks:
      net:
        ipv4_address: 192.168.69.2
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  dhcp1:
    image: dhcp1
    build:
      context: ./dhcp1
      dockerfile: Dockerfile
    container_name: dhcp1
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./dhcp1/nftables.conf:/etc/nftables.conf:ro
      - ./dhcp1/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf:ro
      - ./dhcp1/kea-dhcp6.conf:/etc/kea/kea-dhcp6.conf:ro
      - ./.logs/dhcp1:/var/log/kea
      - dhcp1:/var/lib/postgresql
      - dhcp1_stork:/var/lib/stork-agent
    networks:
      net:
        ipv4_address: 192.168.69.10
    ports:
      - "127.0.0.1:8100:8000"
      - "127.0.0.1:8101:8001"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  dhcp2:
    image: dhcp2
    build:
      context: ./dhcp2
      dockerfile: Dockerfile
    container_name: dhcp2
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./dhcp2/nftables.conf:/etc/nftables.conf:ro
      - ./dhcp2/kea-dhcp4.conf:/etc/kea/kea-dhcp4.conf:ro
      - ./dhcp2/kea-dhcp6.conf:/etc/kea/kea-dhcp6.conf:ro
      - ./.logs/dhcp2:/var/log/kea
      - dhcp2:/var/lib/postgresql
      - dhcp2_stork:/var/lib/stork-agent
    networks:
      net:
        ipv4_address: 192.168.69.11
    ports:
      - "127.0.0.1:8200:8000"
      - "127.0.0.1:8201:8001"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 5

  backups:
    image: backups
    build:
      context: ./backups
      dockerfile: Dockerfile
    container_name: backups
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    depends_on:
      database:
        condition: service_healthy
      dhcp1:
        condition: service_healthy
      dhcp2:
        condition: service_healthy
    volumes:
      - ./backups/nftables.conf:/etc/nftables.conf:ro
      - backups:/var/lib/postgresql
    networks:
      net:
        ipv4_address: 192.168.69.69
    healthcheck:
        test: ["CMD", "/usr/local/bin/healthcheck.sh"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 20s

  stork:
    image: stork
    build:
      context: ./stork
      dockerfile: Dockerfile
    container_name: stork
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    volumes:
      - ./stork/nftables.conf:/etc/nftables.conf:ro
      - stork:/var/lib/stork
      - stork_db:/var/lib/postgresql
      - prometheus:/var/lib/prometheus
      - grafana:/var/lib/grafana
    networks:
      net:
        ipv4_address: 192.168.69.100
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:9090:9090"
      - "127.0.0.1:3000:3000"
    healthcheck:
        test: ["CMD", "/usr/local/bin/healthcheck.sh"]
        interval: 10s
        timeout: 5s
        retries: 10
        start_period: 20s

volumes:
  database:
    name: database
  dhcp1:
    name: dhcp1
  dhcp1_stork:
    name: dhcp1_stork
  dhcp2:
    name: dhcp2
  dhcp2_stork:
    name: dhcp2_stork
  backups:
    name: backups
  stork:
    name: stork
  stork_db:
    name: stork_db
  prometheus:
    name: prometheus
  grafana:
    name: grafana

networks:
  net:
    name: net
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.69.0/24
