flush ruleset

table inet filter {
  set management {
    type ipv4_addr
    flags interval
    elements = { 172.17.1.0/24, 172.17.2.0/24 }
  }

  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept
    ct state invalid drop
    ct state { established, related } accept
    ip protocol icmp accept

    meta l4proto tcp jump input_tcp
    meta l4proto udp jump input_udp
  }

  chain input_tcp {
    ip saddr 192.168.69.1 tcp dport { 8000, 8001 } accept comment "host localhost-published Kea API"
    ip saddr @management tcp dport { 8000, 8001 } accept comment "management Kea API"
    ip saddr { 192.168.69.10, 192.168.69.11 } tcp dport { 9000, 9001 } accept comment "HA peer traffic"
    ip saddr 192.168.69.100 tcp dport 8080 accept comment "Stork agent control"
    ip saddr 192.168.69.100 tcp dport 9547 accept comment "Prometheus scrape via Stork"
    ip saddr 192.168.69.69 tcp dport 5432 accept comment "lease DB replication"
  }

  chain input_udp {
    udp dport 67 accept comment "DHCPv4 server"
    udp dport 547 accept comment "DHCPv6 server"
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
