options {
  directory "/var/cache/bind";
  pid-file "/var/cache/bind/named.pid";
  session-keyfile "/var/cache/bind/session.key";
  listen-on { any; };
  listen-on-v6 { any; };
  allow-query { any; };
  allow-recursion { none; };
  recursion no;
  dnssec-validation no;
  auth-nxdomain no;
  minimal-responses yes;
  zone-statistics yes;
};

statistics-channels {
  inet 127.0.0.1 port 8053 allow { 127.0.0.1; };
};

zone "example.com" {
  type secondary;
  file "/var/cache/bind/slave/db.example.com";
  masters { 192.168.69.200; };
  allow-notify { 192.168.69.200; };
};

zone "3.0.192.in-addr.arpa" {
  type secondary;
  file "/var/cache/bind/slave/db.3.0.192";
  masters { 192.168.69.200; };
  allow-notify { 192.168.69.200; };
};

zone "1.0.0.0.9.6.0.0.9.6.0.0.9.6.d.f.ip6.arpa" {
  type secondary;
  file "/var/cache/bind/slave/db.1.0.0.0.9.6.0.0.9.6.0.0.9.6.d.f.ip6.arpa";
  masters { 192.168.69.200; };
  allow-notify { 192.168.69.200; };
};
