options {
  directory "/var/cache/bind";
  pid-file "/var/cache/bind/named.pid";
  session-keyfile "/var/cache/bind/session.key";
  listen-on { any; };
  listen-on-v6 { any; };
  allow-query { any; };
  allow-recursion { none; };
  recursion no;
  dnssec-validation no;
  auth-nxdomain no;
  minimal-responses yes;
  zone-statistics yes;
};

statistics-channels {
  inet 127.0.0.1 port 8053 allow { 127.0.0.1; };
};

key "kea-ddns-key" {
  algorithm hmac-sha256;
  secret "J7eVnYH4rY8gYz4j5A9LxK2pQm7nS3tVw2yB6cD9fG0=";
};

zone "example.com" {
  type primary;
  file "/var/cache/bind/primary/db.example.com";
  allow-update { key "kea-ddns-key"; };
  allow-transfer { 192.168.69.201; };
  also-notify { 192.168.69.201; };
  notify yes;
};

zone "3.0.192.in-addr.arpa" {
  type primary;
  file "/var/cache/bind/primary/db.3.0.192";
  allow-update { key "kea-ddns-key"; };
  allow-transfer { 192.168.69.201; };
  also-notify { 192.168.69.201; };
  notify yes;
};

zone "1.0.0.0.9.6.0.0.9.6.0.0.9.6.d.f.ip6.arpa" {
  type primary;
  file "/var/cache/bind/primary/db.1.0.0.0.9.6.0.0.9.6.0.0.9.6.d.f.ip6.arpa";
  allow-update { key "kea-ddns-key"; };
  allow-transfer { 192.168.69.201; };
  also-notify { 192.168.69.201; };
  notify yes;
};
