flush ruleset

table inet filter {
  chain input {
    type filter hook input priority filter; policy drop;

    iif lo accept
    ct state invalid drop
    ct state { established, related } accept
    ip protocol icmp accept
    ip6 nexthdr ipv6-icmp accept

    ip saddr 192.168.69.0/24 udp dport 53 accept comment "DNS queries"
    ip saddr 192.168.69.0/24 tcp dport 53 accept comment "DNS queries and zone transfers"
    ip6 saddr fd69:69:69::/64 udp dport 53 accept comment "DNS queries"
    ip6 saddr fd69:69:69::/64 tcp dport 53 accept comment "DNS queries and zone transfers"
    ip saddr 192.168.69.100 tcp dport 9119 accept comment "Prometheus scrape from stork"
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
  }

  chain output {
    type filter hook output priority filter; policy accept;
  }
}
